2022-01-11 10:50:47.643251: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-11 10:50:48.725735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10421 MB memory:  -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:89:00.0, compute capability: 6.1
/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/legacy_tf_layers/core.py:336: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  warnings.warn('`tf.layers.flatten` is deprecated and '
2022-01-11 10:50:53.760350: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2022-01-11 10:50:54.248051: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-11 10:50:54.249345: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-11 10:50:54.249384: W tensorflow/stream_executor/gpu/asm_compiler.cc:77] Couldn't get ptxas version string: Internal: Couldn't invoke ptxas --version
2022-01-11 10:50:54.250842: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-11 10:50:54.251044: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Failed to launch ptxas
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
Step 20: 1 / 6, Inference on sample 000001
Step 20: 2 / 6, Inference on sample 000002
Step 20: 3 / 6, Inference on sample 000004
Step 20: 4 / 6, Inference on sample 000005
Step 20: 5 / 6, Inference on sample 000006
Step 20: 6 / 6, Inference on sample 000008
Feed dict time:
Min:  0.50083
Max:  0.85632
Mean:  0.59035
Median:  0.55009
Inference time:
Min:  0.21251
Max:  3.9436
Mean:  0.92071
Median:  0.3378

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions/kitti_native_eval/0.1_val/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 1
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions/kitti_native_eval/ first 1
20
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions/proposals_and_scores/val/20
mkdir: cannot create directory ‘0.1_val/20/plot’: File exists
sh: 1: gnuplot: not found
sh: 1: gnuplot: not found
sh: 1: gnuplot: not found
sh: 1: gnuplot: not found
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions/kitti_native_eval/
sh: 1: gnuplot: not found
20
sh: 1: gnuplot: not found
  done.
car_detection AP: 0.000000 0.000000 0.000000
car_detection_BEV AP: 0.000000 0.000000 0.000000
car_heading_BEV AP: 0.000000 0.000000 0.000000
car_detection_3D AP: 0.000000 0.000000 0.000000
car_heading_3D AP: 0.000000 0.000000 0.000000
test_results_0.1_val.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val.txt': No such file or directory
mkdir: cannot create directory ‘0.1_val/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000002.txt of ground truth. Please write me an email!
An error occured while processing your results.
test_results_05_iou_0.1_val.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou/ print run_eval_05_iou.sh
cp: cannot stat 'test_results_05_iou_0.1_val.txt': No such file or directory
2022-01-11 10:51:05.833209: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-11 10:51:06.759504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10421 MB memory:  -> device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:89:00.0, compute capability: 6.1
/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/opt/conda/lib/python3.9/site-packages/tensorflow/python/keras/legacy_tf_layers/core.py:336: UserWarning: `tf.layers.flatten` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Flatten` instead.
  warnings.warn('`tf.layers.flatten` is deprecated and '
2022-01-11 10:51:12.377861: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8201
2022-01-11 10:51:12.914870: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-11 10:51:12.915776: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-11 10:51:12.915831: W tensorflow/stream_executor/gpu/asm_compiler.cc:77] Couldn't get ptxas version string: Internal: Couldn't invoke ptxas --version
2022-01-11 10:51:12.917273: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-01-11 10:51:12.917430: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Failed to launch ptxas
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
Step 20: 1 / 6, Inference on sample 000001 (image Rep:1/5)
Step 20: 2 / 6, Inference on sample 000002 (image Rep:1/5)
Step 20: 3 / 6, Inference on sample 000004 (image Rep:1/5)
Step 20: 4 / 6, Inference on sample 000005 (image Rep:1/5)
Step 20: 5 / 6, Inference on sample 000006 (image Rep:1/5)
Step 20: 6 / 6, Inference on sample 000008 (image Rep:1/5)
Feed dict time:
Min:  0.69125
Max:  0.92354
Mean:  0.80243
Median:  0.79619
Inference time:
Min:  0.2853
Max:  4.18653
Mean:  0.98407
Median:  0.34341

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/0.1_val_0_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_0_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/image/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_0_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_0_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000005.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/image/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (image Rep:2/5)
Step 20: 2 / 6, Inference on sample 000002 (image Rep:2/5)
Step 20: 3 / 6, Inference on sample 000004 (image Rep:2/5)
Step 20: 4 / 6, Inference on sample 000005 (image Rep:2/5)
Step 20: 5 / 6, Inference on sample 000006 (image Rep:2/5)
Step 20: 6 / 6, Inference on sample 000008 (image Rep:2/5)
Feed dict time:
Min:  0.73457
Max:  1.11254
Mean:  0.84608
Median:  0.79626
Inference time:
Min:  0.10908
Max:  0.26065
Mean:  0.20516
Median:  0.20985

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/0.1_val_1_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_1_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/image/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_1_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_1_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000004.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/image/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (image Rep:3/5)
Step 20: 2 / 6, Inference on sample 000002 (image Rep:3/5)
Step 20: 3 / 6, Inference on sample 000004 (image Rep:3/5)
Step 20: 4 / 6, Inference on sample 000005 (image Rep:3/5)
Step 20: 5 / 6, Inference on sample 000006 (image Rep:3/5)
Step 20: 6 / 6, Inference on sample 000008 (image Rep:3/5)
Feed dict time:
Min:  0.74674
Max:  0.95943
Mean:  0.83177
Median:  0.82859
Inference time:
Min:  0.20985
Max:  0.23224
Mean:  0.22279
Median:  0.22407

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/0.1_val_2_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_2_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/image/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_2_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_2_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000002.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/image/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (image Rep:4/5)
Step 20: 2 / 6, Inference on sample 000002 (image Rep:4/5)
Step 20: 3 / 6, Inference on sample 000004 (image Rep:4/5)
Step 20: 4 / 6, Inference on sample 000005 (image Rep:4/5)
Step 20: 5 / 6, Inference on sample 000006 (image Rep:4/5)
Step 20: 6 / 6, Inference on sample 000008 (image Rep:4/5)
Feed dict time:
Min:  0.73433
Max:  0.93705
Mean:  0.8177
Median:  0.80782
Inference time:
Min:  0.20587
Max:  0.24666
Mean:  0.23095
Median:  0.23349

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/0.1_val_3_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_3_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/image/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_3_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_3_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000006.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/image/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (image Rep:5/5)
Step 20: 2 / 6, Inference on sample 000002 (image Rep:5/5)
Step 20: 3 / 6, Inference on sample 000004 (image Rep:5/5)
Step 20: 4 / 6, Inference on sample 000005 (image Rep:5/5)
Step 20: 5 / 6, Inference on sample 000006 (image Rep:5/5)
Step 20: 6 / 6, Inference on sample 000008 (image Rep:5/5)
Feed dict time:
Min:  0.69102
Max:  0.96266
Mean:  0.7773
Median:  0.75972
Inference time:
Min:  0.18876
Max:  0.22869
Mean:  0.20707
Median:  0.20547

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/0.1_val_4_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_4_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/image/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_4_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_4_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000001.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/image/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/image/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (lidar Rep:1/5)
Step 20: 2 / 6, Inference on sample 000002 (lidar Rep:1/5)
Step 20: 3 / 6, Inference on sample 000004 (lidar Rep:1/5)
Step 20: 4 / 6, Inference on sample 000005 (lidar Rep:1/5)
Step 20: 5 / 6, Inference on sample 000006 (lidar Rep:1/5)
Step 20: 6 / 6, Inference on sample 000008 (lidar Rep:1/5)
Feed dict time:
Min:  0.54849
Max:  0.85397
Mean:  0.66351
Median:  0.64155
Inference time:
Min:  0.18793
Max:  0.2368
Mean:  0.22647
Median:  0.23463

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/0.1_val_0_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_0_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/lidar/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_0_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_0_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000005.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/lidar/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (lidar Rep:2/5)
Step 20: 2 / 6, Inference on sample 000002 (lidar Rep:2/5)
Step 20: 3 / 6, Inference on sample 000004 (lidar Rep:2/5)
Step 20: 4 / 6, Inference on sample 000005 (lidar Rep:2/5)
Step 20: 5 / 6, Inference on sample 000006 (lidar Rep:2/5)
Step 20: 6 / 6, Inference on sample 000008 (lidar Rep:2/5)
Feed dict time:
Min:  0.53919
Max:  0.82437
Mean:  0.64989
Median:  0.622
Inference time:
Min:  0.19208
Max:  0.25124
Mean:  0.22552
Median:  0.22742

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/0.1_val_1_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_1_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/lidar/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_1_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_1_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000008.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/lidar/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (lidar Rep:3/5)
Step 20: 2 / 6, Inference on sample 000002 (lidar Rep:3/5)
Step 20: 3 / 6, Inference on sample 000004 (lidar Rep:3/5)
Step 20: 4 / 6, Inference on sample 000005 (lidar Rep:3/5)
Step 20: 5 / 6, Inference on sample 000006 (lidar Rep:3/5)
Step 20: 6 / 6, Inference on sample 000008 (lidar Rep:3/5)
Feed dict time:
Min:  0.66399
Max:  0.87307
Mean:  0.80912
Median:  0.8331
Inference time:
Min:  0.21574
Max:  0.24437
Mean:  0.22919
Median:  0.2274

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/0.1_val_2_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_2_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/lidar/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_2_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_2_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000004.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/lidar/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (lidar Rep:4/5)
Step 20: 2 / 6, Inference on sample 000002 (lidar Rep:4/5)
Step 20: 3 / 6, Inference on sample 000004 (lidar Rep:4/5)
Step 20: 4 / 6, Inference on sample 000005 (lidar Rep:4/5)
Step 20: 5 / 6, Inference on sample 000006 (lidar Rep:4/5)
Step 20: 6 / 6, Inference on sample 000008 (lidar Rep:4/5)
Feed dict time:
Min:  0.51322
Max:  0.8657
Mean:  0.70256
Median:  0.71943
Inference time:
Min:  0.20979
Max:  0.23903
Mean:  0.22541
Median:  0.22551

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/0.1_val_3_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_3_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/lidar/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_3_rep.txt': No such file or directory
20
mkdir: cannot create directory ‘0.1_val_3_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000004.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/lidar/': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/proposals_and_scores/val/20
Step 20: 1 / 6, Inference on sample 000001 (lidar Rep:5/5)
Step 20: 2 / 6, Inference on sample 000002 (lidar Rep:5/5)
Step 20: 3 / 6, Inference on sample 000004 (lidar Rep:5/5)
Step 20: 4 / 6, Inference on sample 000005 (lidar Rep:5/5)
Step 20: 5 / 6, Inference on sample 000006 (lidar Rep:5/5)
Step 20: 6 / 6, Inference on sample 000008 (lidar Rep:5/5)
Feed dict time:
Min:  0.48551
Max:  0.77503
Mean:  0.60631
Median:  0.58512
Inference time:
Min:  0.16773
Max:  0.24713
Mean:  0.19978
Median:  0.19655

Global step: 20
Converting detections from: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/final_predictions_and_scores/val/20
3D Detections being saved to: ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/0.1_val_4_rep/20/data
Converting 1 / 6Converting 2 / 6Converting 3 / 6Converting 4 / 6Converting 5 / 6Converting 6 / 6
Num valid: 0
Num samples: 6
../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/kitti_native_eval/ first 1
20
  done.
test_results_0.1_val_4_rep.txt ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/lidar/ print run_eval.sh
cp: cannot stat 'test_results_0.1_val_4_rep.txt': No such file or directory
Step 20: Finished evaluation, results saved to ../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/predictions_sin_rand_5.0_5/lidar/proposals_and_scores/val/20
20
mkdir: cannot create directory ‘0.1_val_4_rep/20/plot_05_iou’: File exists
ERROR: Couldn't read: 000005.txt of ground truth. Please write me an email!
An error occured while processing your results.
cp: cannot create regular file '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_05_iou_sin_rand_5.0_5/lidar/': No such file or directory
Called with args:
Namespace(output_dir='../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs', experiment_config_path='avod/configs/simple/rand_5/evalsin_test.config', data_split='val')
..Working on avod/configs/simple/rand_5/evalsin_test.config
Traceback (most recent call last):
  File "/home/atn001/avod_ssn/./utils_sin/sin_calc_avg_kitti_eval.py", line 301, in <module>
    sys.exit(main(args))
  File "/home/atn001/avod_ssn/./utils_sin/sin_calc_avg_kitti_eval.py", line 266, in main
    calc_avg_scores(args.output_dir,model_config,eval_config,dataset_config,args.data_split)
  File "/home/atn001/avod_ssn/./utils_sin/sin_calc_avg_kitti_eval.py", line 48, in calc_avg_scores
    ckpt_list = get_ckpt_list(os.path.join(res_dir,fname))
  File "/home/atn001/avod_ssn/./utils_sin/sin_calc_avg_kitti_eval.py", line 224, in get_ckpt_list
    with open(res_file,'r') as fid:
FileNotFoundError: [Errno 2] No such file or directory: '../teams/DSC180A_FA21_A00/a15/avod_data/kitti_avod/object/outputs/test/offline_eval/results_sin_rand_5.0_5/image/test_results_0.1_val_0_rep.txt'
